import { productDisplay } from '../types';
import type { DiscoveryResult } from '../types';
import { buildXlsxWorkbook } from './xlsx';
import type { CellValue } from './xlsx';

const CSV_HEADERS = [
  'Host',
  'Port',
  'TLS',
  'Product',
  'Version',
  'Auth Status',
  'Authenticated Status',
  'Role',
  'Mode',
  'OS',
  'Uptime (s)',
  'Latency (ms)',
  'Used Memory (bytes)',
  'Max Memory Policy',
  'Connected Replicas',
  'Master Host',
  'Master Port',
  'Master Link Status',
  'Total Keys',
  'Modules',
  'Cluster State',
  'Run ID',
  'Cert Subject',
  'Cert Issuer',
  'Cert Valid To',
  'Cert Self-Signed',
  'Cert Trusted',
];

function escape(val: string): string {
  if (val.includes(',') || val.includes('"') || val.includes('\n')) {
    return `"${val.replace(/"/g, '""')}"`;
  }
  return val;
}

function totalKeys(r: DiscoveryResult): string {
  if (!r.inventory) return '';
  return String(r.inventory.keyspace.reduce((sum, db) => sum + db.keys, 0));
}

function toRow(r: DiscoveryResult): string {
  return [
    r.host,
    String(r.port),
    String(r.tls),
    productDisplay(r.product),
    r.version ?? '',
    r.anonymousStatus,
    r.authenticatedStatus,
    r.inventory?.role ?? '',
    r.inventory?.mode ?? '',
    r.inventory?.os ?? '',
    r.inventory != null ? String(r.inventory.uptimeSeconds) : '',
    String(r.latency),
    r.inventory?.memory.usedMemoryBytes != null ? String(r.inventory.memory.usedMemoryBytes) : '',
    r.inventory?.memory.maxMemoryPolicy ?? '',
    r.inventory ? String(r.inventory.replication.connectedReplicas.length) : '',
    r.inventory?.replication.masterHost ?? '',
    r.inventory?.replication.masterPort != null ? String(r.inventory.replication.masterPort) : '',
    r.inventory?.replication.masterLinkStatus ?? '',
    totalKeys(r),
    r.inventory?.modules.map((m) => m.name).join(', ') ?? '',
    r.inventory?.clusterInfo?.state ?? '',
    r.inventory?.runId ?? '',
    r.tlsCertificate?.subject ?? '',
    r.tlsCertificate?.issuer ?? '',
    r.tlsCertificate?.validTo ?? '',
    r.tlsCertificate ? String(r.tlsCertificate.selfSigned) : '',
    r.tlsCertificate ? String(r.tlsCertificate.trusted) : '',
  ]
    .map(escape)
    .join(',');
}

export function toCsv(results: DiscoveryResult[]): string {
  const rows = [CSV_HEADERS.join(','), ...results.map(toRow)];
  return rows.join('\r\n') + '\r\n';
}

// Matches the field layout/comments of osstats' config.ini.example
// (https://github.com/Redislabs-Solution-Architects/osstats), so a scan's
// results can be handed straight to that tool. Every key, active or
// commented-out, is padded to the same 12-char column osstats' example uses.
const INI_KEY_WIDTH = 12;

function iniField(key: string, value: string, commented = false): string {
  const prefix = commented ? '; ' : '';
  return `${prefix}${key.padEnd(INI_KEY_WIDTH)}= ${value}`;
}

function toIniSection(r: DiscoveryResult): string {
  return [
    `[${r.host}:${r.port}]`,
    iniField('host', r.host),
    iniField('port', String(r.port)),
    // osstats reads this with configparser's getboolean(), which throws on
    // an empty string — unlike username/password below, this can't be left
    // blank, so it's always written explicitly.
    iniField('tls', r.tls ? 'true' : 'false'),
    '; Username in case ACL access in enabled',
    iniField('username', ''),
    '; Password that applies either in db or user (ACL)',
    iniField('password', ''),
    iniField('ca_cert', '/path/to/ca.crt', true),
    iniField('client_cert', '/path/to/client.crt', true),
    iniField('client_key', '/path/to/client.key', true),
  ].join('\n');
}

/**
 * Renders scan results as an osstats-compatible config.ini: one section per
 * discovered host:port, pre-filled with host/port/tls. Redis Scanner never
 * holds credentials past the request that used them, so username/password
 * are always left blank for the operator to fill in before running osstats.
 */
export function toIni(results: DiscoveryResult[]): string {
  const header =
    '; Generated by Redis Scanner from scan results.\n' +
    '; Fill in username/password (and ca_cert/client_cert/client_key for mTLS)\n' +
    '; before running osstats against these targets.\n';
  return header + '\n' + results.map(toIniSection).join('\n\n') + '\n';
}

// The exact non-throughput column set osstats (https://github.com/Redislabs-
// Solution-Architects/osstats) writes to its "ClusterData" sheet, in its own
// column order. osstats' remaining ~20 columns (Throughput (Ops), GetTypeCmds,
// SetTypeCmds, HashBasedCmds, ...) are throughput deltas — it snapshots INFO
// COMMANDSTATS, waits several minutes, snapshots again, and subtracts. Redis
// Scanner does one point-in-time probe with no held-open connection or wait,
// so it has no data for those columns and — deliberately — doesn't fabricate
// zeros or blanks for them; they're omitted from this sheet entirely.
const OSSTATS_HEADERS = [
  'Source',
  'ClusterId',
  'NodeId',
  'NodeRole',
  'RedisVersion',
  'OS',
  'TotalSystemMemory',
  'BytesUsedForCache',
  'CurrConnections',
  'ClusterEnabled',
  'ConnectedSlaves',
  'MemoryUsed (Gb)',
  'CurrItems',
  'Namespaces',
];

function gb(bytes: number | null): number | null {
  return bytes != null ? Math.round((bytes / 1024 ** 3) * 1000) / 1000 : null;
}

function toOsstatsRow(r: DiscoveryResult): CellValue[] {
  const inv = r.inventory;
  const role = inv?.role === 'master' ? 'Master' : inv?.role === 'replica' ? 'Replica' : null;
  const namespaces = inv?.keyspace.map((db) => `db${db.db}:${db.keys}`).join(', ') ?? null;
  const currItems = inv ? inv.keyspace.reduce((sum, db) => sum + db.keys, 0) : null;

  return [
    productDisplay(r.product),
    null, // ClusterId — osstats groups nodes under a config-file section name; Scanner scans each host:port independently, with no such grouping to report
    r.host,
    role,
    r.version,
    inv?.os ?? null,
    gb(inv?.memory.totalSystemMemoryBytes ?? null),
    inv?.memory.usedMemoryPeakBytes ?? null,
    inv?.connectedClients ?? null,
    inv ? (inv.mode === 'cluster' ? 1 : 0) : null,
    inv ? inv.replication.connectedReplicas.length : null,
    gb(inv?.memory.usedMemoryPeakBytes ?? null),
    currItems,
    namespaces,
  ];
}

/**
 * Renders scan results as an .xlsx shaped like osstats' own output — same
 * sheet name and column layout, populated only with what Redis Scanner's
 * single-probe model actually knows. See OSSTATS_HEADERS for why the
 * throughput columns aren't included.
 */
export function toOsstatsXlsx(results: DiscoveryResult[]): Buffer {
  return buildXlsxWorkbook('ClusterData', OSSTATS_HEADERS, results.map(toOsstatsRow));
}
